---
Name: approutes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    "api/game//$Action": 'App\Controllers\GameAPIController'
    "//$Action": 'App\Controllers\GameController'
    "game//$Action": 'App\Controllers\GameController'
